language: go

go:
  - 1.9

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.13.1 && go install && cd -
  - glide install

script:
  - make test