version: '3.6'

services:

### API #########################################################
    api-php:
        image: gcr.io/google-appengine/php72:latest
        volumes:
            - ./service/api:/app
            - ./service/api/nginx-app.conf:/etc/nginx/conf.d/nginx-app.conf
            - ./service/api/php.ini:/opt/php71/lib/php.ini
        depends_on:
            - api-mysql
        ports:
            - 80:8080
        environment:
            AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
            AWS_S3_KEY: ${AWS_S3_KEY}
            AWS_S3_REGION: ${AWS_S3_REGION}
            AWS_S3_SECRET: ${AWS_S3_SECRET}
            AWS_S3_VERSION: ${AWS_S3_VERSION}
            AWS_SQS_KEY: ${AWS_SQS_KEY}
            AWS_SQS_QUEUE_NAME: ${AWS_SQS_QUEUE_NAME}
            AWS_SQS_REGION: ${AWS_SQS_REGION}
            AWS_SQS_SECRET: ${AWS_SQS_SECRET}
            AWS_SQS_VERSION: ${AWS_SQS_VERSION}
            DOCUMENT_ROOT: /app/wordpress
            GOOGLE_APPLICATION_CREDENTIALS: /app/service-account.json

    api-mysql:
        image: mariadb:10.3
        ports:
            - 3306:3306
        volumes:
            - ./data/api/mysql:/var/lib/mysql
            - ./service/api/wptests.sql:/docker-entrypoint-initdb.d/wptests.sql
        environment:
            MYSQL_DATABASE: ${API_LOCAL_SQL_DB}
            MYSQL_PASSWORD: ${API_LOCAL_SQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${API_LOCAL_SQL_ROOT_PASSWORD}
            MYSQL_USER: ${API_LOCAL_SQL_USER}

### Lighthouse Server ###########################################
    lighthouse-server:
        image: ${LH_GKE_IMAGE}:latest
        volumes:
            - ./data/lighthouse-server:/srv/data
        environment:
            TIDE_API_AUTH_URL: ${TIDE_API_AUTH_URL}
            TIDE_API_HOST: ${TIDE_API_HOST}
            TIDE_API_PROTOCOL: ${TIDE_API_PROTOCOL}
            TIDE_API_KEY: ${TIDE_API_KEY}
            TIDE_API_SECRET: ${TIDE_API_SECRET}
            TIDE_API_VERSION: ${TIDE_API_VERSION}
            LH_SQS_VERSION: ${LH_SQS_VERSION}
            LH_SQS_REGION: ${LH_SQS_REGION}
            LH_SQS_KEY: ${LH_SQS_KEY}
            LH_SQS_SECRET: ${LH_SQS_SECRET}
            LH_SQS_QUEUE_NAME: ${LH_SQS_QUEUE_NAME}
            LH_S3_REGION: ${LH_S3_REGION}
            LH_S3_KEY: ${LH_S3_KEY}
            LH_S3_SECRET: ${LH_S3_SECRET}
            LH_S3_BUCKET_NAME: ${LH_S3_BUCKET_NAME}
            LH_CONCURRENT_AUDITS: ${LH_CONCURRENT_AUDITS}
        network_mode: host

### PHPCS Server ################################################
    phpcs-server:
        image: ${PHPCS_GKE_IMAGE}:latest
        volumes:
            - ./data/phpcs-server:/srv/data
        environment:
            TIDE_API_AUTH_URL: ${TIDE_API_AUTH_URL}
            TIDE_API_HOST: ${TIDE_API_HOST}
            TIDE_API_PROTOCOL: ${TIDE_API_PROTOCOL}
            TIDE_API_KEY: ${TIDE_API_KEY}
            TIDE_API_SECRET: ${TIDE_API_SECRET}
            TIDE_API_VERSION: ${TIDE_API_VERSION}
            PHPCS_SQS_VERSION: ${PHPCS_SQS_VERSION}
            PHPCS_SQS_REGION: ${PHPCS_SQS_REGION}
            PHPCS_SQS_KEY: ${PHPCS_SQS_KEY}
            PHPCS_SQS_SECRET: ${PHPCS_SQS_SECRET}
            PHPCS_SQS_QUEUE_NAME: ${PHPCS_SQS_QUEUE_NAME}
            PHPCS_S3_REGION: ${PHPCS_S3_REGION}
            PHPCS_S3_KEY: ${PHPCS_S3_KEY}
            PHPCS_S3_SECRET: ${PHPCS_S3_SECRET}
            PHPCS_S3_BUCKET_NAME: ${PHPCS_S3_BUCKET_NAME}
            PHPCS_CONCURRENT_AUDITS: ${PHPCS_CONCURRENT_AUDITS}
            PHPCS_TEMP_FOLDER: ${PHPCS_TEMP_FOLDER}
        network_mode: host

### Sync Server #################################################
    sync-server:
        image: ${SYNC_GKE_IMAGE}:latest
        volumes:
            - ./data/sync-server:/srv/data
        environment:
            TIDE_API_HOST: ${TIDE_API_HOST}
            TIDE_API_PROTOCOL: ${TIDE_API_PROTOCOL}
            TIDE_API_VERSION: ${TIDE_API_VERSION}
            SYNC_ACTIVE: ${SYNC_ACTIVE}
            SYNC_API_BROWSE_CATEGORY: ${SYNC_API_BROWSE_CATEGORY}
            SYNC_DATA: ${SYNC_DATA}
            SYNC_DEFAULT_CLIENT: ${SYNC_DEFAULT_CLIENT}
            SYNC_DEFAULT_VISIBILITY: ${SYNC_DEFAULT_VISIBILITY}
            SYNC_FORCE_AUDITS: ${SYNC_FORCE_AUDITS}
            SYNC_ITEMS_PER_PAGE: ${SYNC_ITEMS_PER_PAGE}
            SYNC_POOL_DELAY: ${SYNC_POOL_DELAY}
            SYNC_POOL_WORKERS: ${SYNC_POOL_WORKERS}
            PHPCS_SQS_KEY: ${PHPCS_SQS_KEY}
            PHPCS_SQS_QUEUE: ${PHPCS_SQS_QUEUE}
            PHPCS_SQS_QUEUE_NAME: ${PHPCS_SQS_QUEUE_NAME}
            PHPCS_SQS_REGION: ${PHPCS_SQS_REGION}
            PHPCS_SQS_SECRET: ${PHPCS_SQS_SECRET}
            LH_SQS_KEY: ${LH_SQS_KEY}
            LH_SQS_QUEUE: ${LH_SQS_QUEUE}
            LH_SQS_QUEUE_NAME: ${LH_SQS_QUEUE_NAME}
            LH_SQS_REGION: ${LH_SQS_REGION}
            LH_SQS_SECRET: ${LH_SQS_SECRET}
        network_mode: host
